/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  static const String PLUGIN_NAME = 'brokr_prueba';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String LOGO_SPLASH = 'assets/images/logo_splash.png';
  static const String GOOGLE_ICON = 'assets/svg/google_icon.svg';
}
